/**
 * Order status options 
 */
const ORDER_STATUS={
    REQUESTED:"REQUESTED",
    CANCELLED:"CANCELLED",
    WAITINGTOPAY:"WAITINGTOPAY",
    PAID:"PAID",
    PREPAIRING:"PREPAIRING",
    PACKED:"PACKED",
    WAITINGFORPICKUP:"WAITINGFORPICKUP",
    UNDELIVERED:"UNDELIVERED",
    DELIVERED:"DELIVERED",
    WAITINGTOREFUND:"WAITINGTOREFUND",
    REFUNDED:"REFUNDED"
}
/**
 * Exporting the order status 
 */
export default ORDER_STATUS